data_load:
  dataset: 'data/raw/data.csv'
  target: 'Target'
  test: 0.2

datasets:
  path_xtrain: 'data/raw/xtrain.csv'
  path_ytrain: 'data/raw/ytrain.csv'
  path_xtest: 'data/raw/xtest.csv'
  path_ytest: 'data/raw/ytest.csv'

processed:
  path_xtrain: 'data/processed/xtrain.csv'
  path_xtest: 'data/processed/xtest.csv'

features:
  scaler: ['Age at enrollment', 'Unemployment rate', 'Inflation rate', 'GDP']
  log: ['Previous qualification (grade)','Admission grade', 'Curricular units 1st sem (credited)', 'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)', 'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)', 'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)', 'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)', 'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)', 'Curricular units 2nd sem (without evaluations)']
  
tuning:
  parameters: { 'RF': 
                {
                        'n_estimators': [50, 100, 200],
                        'max_depth': [None, 10, 20, 30],
                        'min_samples_split': [2, 5, 10],
                        'criterion':['log_loss', 'entropy', 'gini'],
                        'max_features':['sqrt', 'log2'],
                        'bootstrap':[True,False],
                        'class_weight':['balanced', 'balanced_subsample']
                },
                'SVC': {
                        'C': [0.1, 1, 3, 5],
                        'gamma':[0.005, 0.5, 0.05, 0,.01],
                        'kernel': ['linear', 'rbf']
                },        
                'KNN': {
                        'n_neighbors': [3, 5, 9, 12, 15, 17, 21],
                        'weights': ['uniform', 'distance'],
                        'algorithm': ['auto', 'ball_tree', 'kd_tree'],
                        'leaf_size': [10, 20, 30, 40, 50]
                },
                'LR':{
                    'C':[1,5,10],
                    'solver':['lbfgs', 'newton-cg', 'sag', 'saga']
                },
                'DTree': {
                    'min_samples_split':[1,3,5,10],
                    'max_depth':[5,10,15,20],
                    'max_leaf_nodes':[2,3,5,7,10],
                    'criterion':['log_loss', 'entropy', 'gini'],
                    'splitter':['best', 'random']
                },
              }

evaluation: 
  metrics: ['accuracy','precision_macro','recall_macro','f1_macro']
  test_data: 'data/processed/test.csv'

models:
  path_models: 'models/models.sav'
  path_models_class: 'models/models_class.sav'
